config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'steps/index'
  get 'about_us/index'

  resources :courses
  devise_for :users, controllers: {

    registrations: "users/registrations",
    # Add this
    omniauth_callbacks: "users/omniauth_callbacks"
  }


 get 'users/show'

 get 'home/index'
  resources :courses
  resources :charges
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'comments/create'
  root 'home#index'
  resources :purchases
  resources :users, only: [:show]

  resources :courses do
    resources :comments
  end
  resources :conversations do
    resources :messages
  end

  resources :about_us do
    resources :about_us
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :course
    belongs_to :user

    validates :content, presence: true, length: { minimum: 2}

  

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  # The conversation associates the concept of User divided into sender and recipient.
  belongs_to :sender, foreign_key: :sender_id, class_name:'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name:'User'
  # One conversation is one-to-many that contains lots of messages.
  has_many :messages, dependent: :destroy
  # Set validation to prevent [: sender_id,: recipient_id] from being saved in the same combination.
  validates_uniqueness_of :sender_id, scope: :recipient_id
  # Explained below
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
  # Explained below
  def target_user(current_user)
    if sender_id == current_user.id
      User.find(recipient_id)
    elsif recipient_id == current_user.id
      User.find(sender_id)
    end
  end
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :info_title, :info_details, :free_info_topics, :free_info_details,  presence: true
    validates :price, presence:true
    belongs_to :user
    has_many :purchases 
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
    belongs_to :user
    belongs_to :course
    def to_param
        uuid
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :purchases, dependent: :destroy


  has_many :courses, dependent: :destroy
  # Include default devise modules. Others available are:
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,:omniauthable, 
         omniauth_providers: [:google, :facebook, :github, :twitter]
  
  mount_uploader :profile_image, ImageUploader

  
  # #enable user to be saved with random id
  def self.create_unique_string
    SecureRandom.uuid
  end

  #check if the user exists and find user info from other app
  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid, profile_image: auth.info.profile,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end

  def self.find_for_facebook(auth)
    user = User.find_by(email: auth.info.email)
  
    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end

  def self.find_for_github(auth)
    user = User.find_by(email: auth.info.email)
  
    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end


  def self.find_for_twitter(auth)
    user = User.find_by(email: auth.info.email)
  
    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @teachers = User.where(:user_type => 'Teacher')
    @most_liked = Course.all
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!

  def show
      @purchase=Purchase.find_by_uuid(params[:id])
      # @course = Course.find(@purchase.course_id)
  end

  def index
    @purchases=Purchase.all

  end

  def destroy
    @purchase=Purchase.find_by_uuid(params[:id])
    @purchase.destroy
    redirect_to Purchases_url, notice: 'Purchase was successfully destroyed.'
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :set_user, only: [ :show]
  before_action :set_search
  def show
    @conversations = Conversation.all
    @sold_courses = Course.where(:user_id => @user.id)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/purchases/_form.html.erb
<%= form_with(model: purchase, local: true) do |form| %>
  <% if purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% purchase.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :ammount %>
    <%= form.number_field :ammount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchases</h1>

<table>
  <thead>
    <tr>
      <th>Ammount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.ammount %></td>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<div id="purchaseModal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Your purchase is completed</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><strong>Email:
          <%= @purchase.email %></strong>
        </p>
        <p><strong>Amount:
          <%= @purchase.ammount %></strong>
        </p>
        <p><strong>description:
          <%= @purchase.description %></strong>
        </p>
        <p><strong>Currency:
          <%= @purchase.currency %></strong>
        </p>
        <p><strong>card:
          <%= @purchase.card %></strong>
        </p>
        <p><strong>Customer_ID:
          <%= @purchase.user_id %></strong>
        </p>
        <p><strong>course_id:
          <%= @purchase.course_id %></strong>
        </p>
        <p><strong>created_at":
          <%= @purchase.created_at %></strong>
        </p>
        <p><strong>updated_at":
          <%= @purchase.updated_at %></strong>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<script>
	$(document).ready(function(){
		$("#purchaseModal").modal('show');
	});
</script>