config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'steps/index'
  get 'about_us/index'

  resources :courses
  devise_for :users, controllers: {

    registrations: "users/registrations",
    # Add this
    omniauth_callbacks: "users/omniauth_callbacks"
  }


 get 'users/show'

 get 'home/index'
  resources :courses
  resources :charges
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'comments/create'
  root 'home#index'
  resources :purchases
  resources :users, only: [:show]

  resources :courses do
    resources :comments
  end
  resources :conversations do
    resources :messages
  end

  resources :about_us do
    resources :about_us
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :course
    belongs_to :user

    validates :content, presence: true, length: { minimum: 2}

  

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  # The conversation associates the concept of User divided into sender and recipient.
  belongs_to :sender, foreign_key: :sender_id, class_name:'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name:'User'
  # One conversation is one-to-many that contains lots of messages.
  has_many :messages, dependent: :destroy
  # Set validation to prevent [: sender_id,: recipient_id] from being saved in the same combination.
  validates_uniqueness_of :sender_id, scope: :recipient_id
  # Explained below
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
  # Explained below
  def target_user(current_user)
    if sender_id == current_user.id
      User.find(recipient_id)
    elsif recipient_id == current_user.id
      User.find(sender_id)
    end
  end
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :info_title, :info_details, :free_info_topics, :free_info_details,  presence: true
    validates :price, presence:true
    belongs_to :user
    has_many :purchases 
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
    belongs_to :user
    belongs_to :course
    def to_param
        uuid
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :purchases, dependent: :destroy


  has_many :courses, dependent: :destroy
  # Include default devise modules. Others available are:
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,:omniauthable, 
         omniauth_providers: [:google, :facebook, :github, :twitter]
  
  mount_uploader :profile_image, ImageUploader

  
  # #enable user to be saved with random id
  def self.create_unique_string
    SecureRandom.uuid
  end

  #check if the user exists and find user info from other app
  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid, profile_image: auth.info.profile,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end

  def self.find_for_facebook(auth)
    user = User.find_by(email: auth.info.email)
  
    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end

  def self.find_for_github(auth)
    user = User.find_by(email: auth.info.email)
  
    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end


  def self.find_for_twitter(auth)
    user = User.find_by(email: auth.info.email)
  
    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /courses
  def index
      @q = Course.ransack(params[:q])
      if params[:q]
        @courses = @q.result
      else
        @courses = Course.all
      end
  end
  # GET /courses/1
  def show
    @purchased = Purchase.where(user_id: current_user.id).where(course_id: @course.id)
    #Model.where(condition_a: :a).where(condition_b: :b).all
    @comments = @course.comments
    @comment = @course.comments.build
    if @course.comments.average(:rating).present?
      @average_rating = @course.comments.average(:rating).round(2)
    end
  end


  # GET /courses/new
  def new
    @course = Course.new

  end

  # GET /courses/1/edit
  def edit
  end
  def contact_us
     @courses = Course.all

  end


  # POST /courses
  def create
    @course = Course.new(course_params)
    @course.user_id = current_user.id
    if @course.save
      redirect_to @course, notice: 'Course was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /courses/1
  def update
    if @course.update(course_params)
      redirect_to @course, notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /courses/1
  def destroy
    @course.destroy
    redirect_to courses_url, notice: 'Course was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end
    def set_search
      @q = Course.ransack(params[:q])
      @courses = @q.result
    end
    # Only allow a trusted parameter "white list" through.
    def course_params
      params.require(:course).permit(:info_title, :info_details, :free_info_topics, :free_info_details, :price )
    end

    def only_teacher_can_create_course
      if current_user && current_user.user_type == "Teacher"
        redirect_to courses_path, notice: 'You can not create course since you are learner'
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @teachers = User.where(:user_type => 'Teacher')
    @most_liked = Course.all
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :set_user, only: [ :show]
  before_action :set_search
  def show
    @conversations = Conversation.all
    @sold_courses = Course.where(:user_id => @user.id)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<div class="w-75 m-4 mx-auto border rounded bg-light p4">
  <%= form_with(model: course, local: true) do |form| %>
    <% if course.errors.any? %>
      <div id="error_explanation alert alert-danger" role="alert">
        <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

        <ul>
          <% course.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="row">
    <div class="col py-5">
      <div class="field">
        <%= form.text_field :info_title ,class: "form-control w-75 m-auto", placeholder: "Course title"%>
      </div>

      <div class="field">
        <%= form.text_area :info_details ,class: "form-control w-75 m-auto", placeholder: "Course detail", rows:"4"%>
      </div>
    </div>
    <div class="col py-5">
      <div class="field">
        <%= form.text_field :free_info_topics ,class: "form-control w-75 m-auto", placeholder: "Free topic"%>
      </div>

      <div class="field">
        <%= form.text_area :free_info_details,class: "form-control w-75 m-auto", placeholder: "Free topic details", rows:"4" %>
      </div>
      <div class="field">
        <%= form.number_field :price,class: "form-control w-75 m-auto", placeholder: "Price" %>
      </div>

      
  
      <div class="field ">
        <%= form.submit class: "form-control w-75 shadow-sm bg-facebook text-white m-auto"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<h3 class="text-center mt-4">Editing Course details</h3>

<%= render 'form', course: @course %>

app/views/courses/index.html.erb
<div class="container">


<div class="my-4 text-center">
  <h4>Learn A programming skill of your choice!!</h4>
</div>
<div class="mx-auto" style="width: 70%">
  <% if user_signed_in? && current_user.user_type == "Teacher" %>
    <h4><%= link_to 'New Course', new_course_path, class: "text-info" %></h4>
  <% end %>
</div>
    <% @courses.each do |course| %>
    <div class="card mx-auto bg-light shadow-sm m-2" style="width: 70%;">
      <div class="card-body">
        <div class="card-title">
          <h5 class="w-50 float-left"><%= course.info_title %></h5>
          <h4 class="w-50 float-right text-right text-warning">Buy: <%= course.price %>$</h4>
        </div>
        <p class="card-text"><%= course.info_details %></p>
        <%= link_to "Follow course", course_path(course), class: "btn btn-info text-white btn-sm " %>
        <% if user_signed_in? && course.user_id == current_user.id %>
          <%= link_to 'Edit', edit_course_path(course), class: "text-success" %>
          <%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger" %>
        <% end %>
      </div>
    </div>

    <% end %>


</div>

app/views/courses/new.html.erb
<h3 class="text-center mt-4">Register new sale course</h3>

<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<div class="container p-4">
  <div class="card float-left" style="width: 47%;">
    <div class="card-body">
      <div class="card-title pr-3 row">
        <div class="col text-success mr-auto">
          <h5><strong><%= @course.info_title %></strong></h5>
          <h6 class="text-warning"><strong><i class="fas fa-star"></i> Stars: <%= @average_rating %></strong></h6>
        </div>

        <h6><strong><%= link_to 'Visit the teacher', user_path(@course.user), class: "btn btn-success btn-sm shadow-sm text-white" %></strong></h6>
      </div>
      <h6><strong>Tought by <%= @course.user.name %></strong></h6>
      <h6 class="card-subtitle mb-2 text-muted">
        <strong>Buy:</strong>
        <%= @course.price %> $
      </h6><br>
      <p class="card-text">
        <strong>Course details:</strong><br>
        <%= @course.info_details %>
      </p>
      <p class="card-text">
        <strong>Free topics:</strong><br>
        <%= @course.free_info_topics %>
      </p>
      <p class="card-text">
        <strong>Free topic details:</strong><br>
        <%= @course.free_info_details %>
      </p>


      <% if user_signed_in? %>
        <% if @course.user_id == current_user.id %>
          <%= link_to 'Edit course information', edit_course_path(@course), class: "btn btn-success" %>
        <% else %>
        <%= form_tag charges_path, id:'chargeForm' do %>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
          <script src="https://checkout.stripe.com/checkout.js"></script>
          <%= hidden_field_tag 'stripeToken'%>
          <%= hidden_field_tag 'amount', @course.price * 100 %>
          <%= hidden_field_tag 'stripeEmail',current_user.email%>
          <%= hidden_field_tag 'course_id', @course.id %>
          <% if @purchased.present? %>
          <p style = "background-color: green;"><strong> You purchased this course</strong></p>
          <% else %>
          <button id="btn-buy" class= "btn btn-info px-4 shadow "><strong>Pay with card</button>
          <% end %>
        
          <script>
            var handler = StripeCheckout.configure({
            key: '<%= Rails.configuration.stripe[:publishable_key]%>',
            token: function(token, arg){
            document.getElementById("stripeToken").value=token.id;
            document.getElementById("stripeEmail").value=token.email;
            document.getElementById("chargeForm").submit();
              }
            });
            document.getElementById("btn-buy").addEventListener('click',function(e){
            handler.open({
            name: '<%= @course.info_title %> ',
            description: 'buy this course for ($<%= @course.price %>)',
            amount: document.getElementById("amount").value 
            });
            e.preventDefault();
            })
          </script>
        <% end %>
        <% end %>
      <% end %>

    </div>
  </div>

  <div class="card  float-right" style="width: 50%;">
    <div class="card-header">
      <h5 class="text-success">Reviews about the course</h5>
    </div>
    <div class="card_comment card-body">
      <div id="comments_area">
        <!-- Render to display the posted comment list on the blogs detail page -->
        <%= render partial: 'comments/index', locals: { comments: @comments, course: @course } %>
      </div>

    </div>
    <div class="card-footer">
      <%= render partial: 'comments/form', locals: { comment: @comment, course: @course } %>
    </div>
  </div>
</div>