config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'steps/index'
  get 'about_us/index'

  resources :courses
  devise_for :users, controllers: {

    registrations: "users/registrations",
    # Add this
    omniauth_callbacks: "users/omniauth_callbacks"
  }


 get 'users/show'

 get 'home/index'
  resources :courses
  resources :charges
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'comments/create'
  root 'home#index'
  resources :purchases
  resources :users, only: [:show]

  resources :courses do
    resources :comments
  end
  resources :conversations do
    resources :messages
  end

  resources :about_us do
    resources :about_us
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :course
    belongs_to :user

    validates :content, presence: true, length: { minimum: 2}

  

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  # The conversation associates the concept of User divided into sender and recipient.
  belongs_to :sender, foreign_key: :sender_id, class_name:'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name:'User'
  # One conversation is one-to-many that contains lots of messages.
  has_many :messages, dependent: :destroy
  # Set validation to prevent [: sender_id,: recipient_id] from being saved in the same combination.
  validates_uniqueness_of :sender_id, scope: :recipient_id
  # Explained below
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
  # Explained below
  def target_user(current_user)
    if sender_id == current_user.id
      User.find(recipient_id)
    elsif recipient_id == current_user.id
      User.find(sender_id)
    end
  end
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :info_title, :info_details, :free_info_topics, :free_info_details,  presence: true
    validates :price, presence:true
    belongs_to :user
    has_many :purchases 
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
    belongs_to :user
    belongs_to :course
    def to_param
        uuid
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :purchases, dependent: :destroy


  has_many :courses, dependent: :destroy
  # Include default devise modules. Others available are:
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,:omniauthable, 
         omniauth_providers: [:google, :facebook, :github, :twitter]
  
  mount_uploader :profile_image, ImageUploader

  
  # #enable user to be saved with random id
  def self.create_unique_string
    SecureRandom.uuid
  end

  #check if the user exists and find user info from other app
  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid, profile_image: auth.info.profile,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end

  def self.find_for_facebook(auth)
    user = User.find_by(email: auth.info.email)
  
    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end

  def self.find_for_github(auth)
    user = User.find_by(email: auth.info.email)
  
    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end


  def self.find_for_twitter(auth)
    user = User.find_by(email: auth.info.email)
  
    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @teachers = User.where(:user_type => 'Teacher')
    @most_liked = Course.all
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :set_user, only: [ :show]
  before_action :set_search
  def show
    @conversations = Conversation.all
    @sold_courses = Course.where(:user_id => @user.id)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StFirstTimeFree</title>
    <%= favicon_link_tag 'first.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Barlow|Belleza|Buda|Cagliostro|Comfortaa|Imprima|Maven+Pro|Syncopate|Tajawal">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>

<%= javascript_pack_tag 'application', 'data-turbolinks-track' => false %>
    <script src="https://kit.fontawesome.com/472ee2df72.js" crossorigin="anonymous"></script>
    <script type="text/JavaScript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" ></script>


  </head>

  <body>
<!-- navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-light text-pink bg-light sticky-top shadow ">
      <div class="logo">
        <a class="navbar-brand text-pink" href="#"><%= image_tag "logo.png"%></a>
      </div>
      <div class="form-inline w-50">
        <%= search_form_for @q do |f| %>
          <%= f.search_field :info_title_or_info_details_cont, class: "form-control mr-sm-2 rounded-pill", placeholder: "Search course" %>
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav ml-auto my-auto mt-lg-0">
          <li class="nav-item my-auto px-4 border-right">
            <%= link_to 'Home', home_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item my-auto px-4 border-right">
            <%= link_to 'Courses', courses_url, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>

          <li class="nav-item pl-4">
            <% if current_user.admin? %>
              <%= link_to rails_admin_path do %>
                <strong class="text-dark"><%= current_user.name %></strong>
                <% if current_user.profile_image.url %>
                  <%= image_tag current_user.profile_image.url, class: "rounded shadow" %>
                <% else %>
                  <%= image_tag "user_icon.png", class: "rounded-full shadow" %>
                <% end %>
              <% end %>
              <% else %>
                <%= link_to user_path(current_user) do %>
                  <strong class="text-dark"><%= current_user.name %></strong>
                  <% if current_user.profile_image.url %>
                    <%= image_tag current_user.profile_image.url, class: "rounded shadow" %>
                  <% else %>
                    <%= image_tag "user_icon.png", class: "rounded-full shadow" %>
                  <% end %>
                <% end %>
            <% end %>
          </li>
          <li class="nav-item my-auto pl-4">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger text-danger btn-sm text-white shadow nav-link" %>
          </li>

          <% else %>
            <li class="px-4">
              <%= link_to 'Login', new_user_session_path, class: "btn btn-info text-white px-4 shadow" %>
            </li>

          <% end %>
        </ul>
      </div>
    </nav>
<!-- end of navigation bar -->

    <div class="main-body overflow-auto mb-2">
    <% if notice %>
    <div class="alert alert-info">
    <%= notice %>
    </div>
    <% end %>
      <%= yield %>

    </div>

    <div class="card-footer text-pink bg-dark p-4 sticky-bottom">
      <%= image_tag "logo.png"%>
      <div class="row text-pink bg-dark w-75 mt-2">

        <div class="col border-right border-light px-5">
          <strong><%= link_to 'About Us', about_us_path, class: "text-white" %><br></strong>
          <strong><%= link_to 'How it works', steps_index_path, class: "text-white" %><br></strong>

        </div>
        <div class="col border-right border-light">
          <strong><a class="text-pink" href="#"><i class="fab fa-facebook"></i> Facebook</a><br></strong>
          <strong><a class="text-pink" href="#"><i class="fab fa-twitter"></i> Twitter</a><br></strong>
          <strong><a class="text-pink" href="#"><i class="fab fa-google"></i> Google</a></strong>
        </div>
        <div class="col">
          <h5>Contact us</h5>
          <strong><a href="#" class="text-pink"><i class="far fa-envelope"></i> freetimesupport@gmail.com</a></strong><br>
          <strong><a href="#"></a></strong>
        </div>

      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>